period_bands:
  - T017-040s
  - T040-100s

raw_obsd_tag: obsd
raw_synt_tag: synt
proc_obsd_tag: proc_obsd
proc_synt_tag: proc_synt

# Misfit type to compute misfit evaluation
# for line search
misfit_type: misfit_dt 
